name: Fix Json Schemes

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    # Name the Job
    name: Lint client code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./

    steps:
      - uses: actions/checkout@v2
      - run: git pull
      # to fix error with permissions
      # source: https://github.com/actions/virtual-environments/issues/599#issuecomment-605558600
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g fixjson
      - name: format schemes json files
        run: fixjson --write --indent 2 /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes/**/*.json
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot] Automated fixjson update"
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}